name: Go
on: push
env:
  DEBUG: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.21'
        - '1.22'
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: |
        # just for file path from stacks.
        mkdir -p /home/runner/go/src/github.com/xgfone/go-defaults
        cp -r ./* /home/runner/go/src/github.com/xgfone/go-defaults
        cd /home/runner/go/src/github.com/xgfone/go-defaults
        go test -cover -race ./...
